sudo: false
language: python
python:
    - 3.6
    - 3.9
script:
- creds=local.json make test

deploy:
    provider: pypi
    username: "__token__"
    password: ${PYPI_API_KEY}
    on:
        branch: master
        python: 3.9
        skip_existing: true